// AUTO-GENERATED — do not edit by hand.
// Regenerate via: node cli/scripts/generate-registry.mjs

export interface RegistryEntry {
  name: string
  title: string
  description: string
  files: string[]
  dependencies: string[]
  shadcnComponents: string[]
  devDependencies?: string[]
}

export const registry: RegistryEntry[] = [
  {
    name: "halo",
    title: "Halo",
    description: "Cursor-reactive WebGL background. Single OGL fragment shader paints a dense iridescent dot grid; cursor warps the UVs with a Gaussian-falloff swirl so the grid visibly bends + spirals around the pointer, velocity smears the pattern, an accent halo brightens the cursor neighborhood.",
    files: ["halo.tsx"],
    dependencies: ["ogl"],
    shadcnComponents: [],
  },
  {
    name: "aurora",
    title: "Aurora",
    description: "Fullscreen OGL fragment shader. Four-octave value noise warped with curl-ish offsets, mapped through a 3-color gradient to paint living aurora bands.",
    files: ["aurora.tsx"],
    dependencies: ["ogl"],
    shadcnComponents: [],
  },
  {
    name: "nebula",
    title: "Nebula",
    description: "Cosmic dust cloud with stars (OGL shader). Two parallax layers of 4-octave fbm noise generate cloud density with depth; star field overlay twinkles via sin-based brightness variation.",
    files: ["nebula.tsx"],
    dependencies: ["ogl"],
    shadcnComponents: [],
  },
  {
    name: "mesh-gradient",
    title: "Mesh Gradient",
    description: "Stripe-homepage-style fluid mesh gradient (OGL shader). Five colored blobs drift around the canvas; soft falloff + chained mix() melt adjacent colors into each other.",
    files: ["mesh-gradient.tsx"],
    dependencies: ["ogl"],
    shadcnComponents: [],
  },
  {
    name: "hyperspeed",
    title: "Hyperspeed",
    description: "Fullscreen OGL fragment shader. Warp-speed star streaks: each pixel marches outward through layered seeded star fields. Single triangle, pure GLSL.",
    files: ["hyperspeed.tsx"],
    dependencies: ["ogl"],
    shadcnComponents: [],
  },
  {
    name: "particle-field",
    title: "Particle Field",
    description: "WebGL particle field (Three.js). 8000 GL points in a grid; cursor raycasts onto a plane and pushes nearby particles outward with quadratic falloff. Single draw call, custom point shader.",
    files: ["particle-field.tsx"],
    dependencies: ["three"],
    shadcnComponents: [],
  },
  {
    name: "spotlight-tour",
    title: "Spotlight Tour",
    description: "Interactive onboarding overlay. Dim the page, cut a soft-cornered glowing hole around the active target via the box-shadow technique, anchor a tooltip with prev/next/skip and step dots. Auto-measure, auto-scroll, auto-flip placement, keyboard nav.",
    files: ["spotlight-tour.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "live-cursors",
    title: "Live Cursors",
    description: "Figma/Vercel-style multiplayer cursors with colored chat bubbles. Spring-driven movement, optional typing dots, white bubbles that pop on a dark canvas.",
    files: ["live-cursors.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "cmd-bar",
    title: "Cmd Bar 2.0",
    description: "Raycast-style command palette with a right-side preview pane. Arrow-key through results and the preview swaps live to show context for the highlighted item.",
    files: ["cmd-bar.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "ai-chat",
    title: "AI Chat",
    description: "Claude/ChatGPT-style chat view with streaming text (char-by-char with a blinking caret), a thinking 3-dot indicator, and user + assistant avatars.",
    files: ["ai-chat.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "notification-stack",
    title: "Notification Stack",
    description: "iOS-style stacked notifications. Cards peek behind the top one when collapsed; hover fans them out with spring physics; click ✕ to dismiss with a slide-out.",
    files: ["notification-stack.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "dynamic-island",
    title: "Dynamic Island",
    description: "iPhone-style notch that morphs smoothly between rich states — idle, ring, timer, record, music, maps, airdrop. Spring-physics layout animation.",
    files: ["dynamic-island/index.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "schema",
    title: "Schema",
    description: "Mini database ER diagram. Tables render as cards with column rows; SVG bezier lines draw between every foreign-key column and the row it references.",
    files: ["schema.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "terminal",
    title: "Terminal",
    description: "Live-looking terminal that auto-types a scripted sequence of commands + outputs. Mac-style header, blinking cursor, pause-on-hover, play/pause/replay controls, optional looping.",
    files: ["terminal.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "deploy",
    title: "Deploy",
    description: "Vercel-style deployment card. Status drives the visual: queued / building (shimmer + live elapsed counter) / ready (soft pulse) / failed (shake) / cancelled.",
    files: ["deploy.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "portal-scroll",
    title: "Portal Scroll",
    description: "Pinned scroll section built around one image: you're outside a moody scene, a circular portal opens in the centre and grows to consume the viewport, revealing a completely different scene inside. Cursor parallax inside the portal sells the depth, the inner headline arrives letter-by-letter, and a spinning conic-gradient rim with a scan dot rides the portal edge until it fills the screen.",
    files: ["portal-scroll.tsx"],
    dependencies: ["@gsap/react","gsap","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "cinema-reel",
    title: "Cinema Reel",
    description: "A pinned scroll section that unspools a horizontal film strip from vertical scroll. Reel hubs spin at the edges, sprocket holes line the top and bottom, the centered frame pops forward, and the rest dim — like a real projector.",
    files: ["cinema-reel.tsx"],
    dependencies: ["@gsap/react","active","gsap","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "vinyl-player",
    title: "Vinyl Player",
    description: "A turntable with a spinning vinyl record + tonearm that rotates to drop into each track. Per-track info panel + a live waveform highlights the active track. Pure scroll-driven motion.",
    files: ["vinyl-player.tsx"],
    dependencies: ["@gsap/react","gsap","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "drag-to-confirm",
    title: "Drag to Confirm",
    description: "iOS slide-to-unlock pattern. Draggable knob on a pill track with a color fill that grows with progress. Release past threshold confirms; release before springs back.",
    files: ["drag-to-confirm.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "app-shell",
    title: "App Shell",
    description: "The layout primitive every SaaS starts with. Collapsible left rail (brand + sections + footer), optional topbar, main content. Mobile drawer, active highlight via layoutId.",
    files: ["app-shell.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "browser-window",
    title: "Browser Window",
    description: "Mac-style window chrome wrapper. Traffic lights, optional back/forward/reload, URL bar with optional char-by-char animated typing. Dark + light variants.",
    files: ["browser-window.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "code-window",
    title: "Code Window",
    description: "Static syntax-highlighted code in a mac-style window frame. Hand-rolled tokeniser, line numbers, copy button, optional line highlighting.",
    files: ["code-window.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "profile-card",
    title: "Profile Card",
    description: "GitHub-style hover preview card. Gradient header, avatar overlapping the seam, bio + meta + stats + primary/secondary actions.",
    files: ["profile-card.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "avatar-status",
    title: "Avatar with Status",
    description: "Avatar primitive with initials fallback (deterministic color from name hash), corner status dot (online/away/busy/offline), and optional name + role. Online pulses.",
    files: ["avatar-status.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "phone-input",
    title: "Phone Input",
    description: "International phone input with searchable country selector, as-you-type formatting, and E.164 output.",
    files: ["phone-input.tsx"],
    dependencies: ["framer-motion","libphonenumber-js","lucide-react"],
    shadcnComponents: ["command","input","popover"],
  },
  {
    name: "stepper",
    title: "Stepper",
    description: "Multi-step progress indicator with horizontal/vertical layout, clickable navigation, and error states.",
    files: ["stepper.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "number-input",
    title: "Number Input",
    description: "Stepper-flanked numeric input with long-press, keyboard nav, and Intl number formatting.",
    files: ["number-input.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: ["button","input"],
  },
  {
    name: "multi-step-form",
    title: "Multi-Step Form",
    description: "Wizard built on React Hook Form with per-step Zod validation and animated transitions.",
    files: ["multi-step-form.tsx"],
    dependencies: ["framer-motion","lucide-react","react-hook-form","zod"],
    shadcnComponents: ["button"],
  },
  {
    name: "date-range-picker",
    title: "Date Range Picker",
    description: "Two-month range picker with preset shortcuts, popover on desktop, and drawer on mobile.",
    files: ["date-range-picker.tsx"],
    dependencies: ["date-fns","framer-motion","lucide-react","react-day-picker"],
    shadcnComponents: ["button","calendar","drawer","popover"],
  },
  {
    name: "autocomplete",
    title: "Autocomplete",
    description: "Static, async, and creatable combobox with single and multi-select, debounced search, and chip UI.",
    files: ["autocomplete/chip.tsx","autocomplete/empty.tsx","autocomplete/index.tsx","autocomplete/loading.tsx","autocomplete/option-item.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: ["command","popover"],
  },
  {
    name: "timeline",
    title: "Timeline",
    description: "Four variants: vertical, alternating, horizontal, and activity feed. Scroll-driven line animation, live updates, expandable events.",
    files: ["timeline/activity-feed.tsx","timeline/alternating-timeline.tsx","timeline/centered-timeline.tsx","timeline/date-separator.tsx","timeline/default-timeline.tsx","timeline/index.tsx","timeline/timeline-connector.tsx","timeline/timeline-dot.tsx","timeline/timeline-event.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: ["avatar","badge"],
  },
  {
    name: "otp-input",
    title: "OTP Input",
    description: "One-time password input with animated character boxes, paste support, auto-focus navigation, and error/success states.",
    files: ["otp-input.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "tags-input",
    title: "Tags Input",
    description: "Multi-tag text input with chip UI, auto-suggestions, validation, and animated add/remove transitions.",
    files: ["tags-input.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: ["badge"],
  },
  {
    name: "color-picker",
    title: "Color Picker",
    description: "Full-featured color picker with saturation canvas, hue slider, swatches palette, format switching, and color history.",
    files: ["color-picker/index.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: ["popover","tabs"],
  },
  {
    name: "image-cropper",
    title: "Image Cropper",
    description: "Canvas-based image cropper with drag-to-crop, zoom, rotation, flip, aspect ratio presets, and file output.",
    files: ["image-cropper/index.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: ["button","dialog","slider"],
  },
  {
    name: "signature-pad",
    title: "Signature Pad",
    description: "Canvas-based signature pad with draw and type modes, bezier smoothing, velocity-based stroke width, and export to PNG/JPEG/SVG.",
    files: ["signature-pad/draw-canvas.tsx","signature-pad/index.tsx","signature-pad/stroke-utils.ts","signature-pad/type-canvas.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "json-editor",
    title: "JSON Editor",
    description: "Interactive JSON editor with tree view, raw editing, inline value editing, type badges, and copy support.",
    files: ["json-editor/index.tsx","json-editor/raw-editor.tsx","json-editor/tree-node.tsx","json-editor/type-badge.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "mention-input",
    title: "Mention Input",
    description: "ContentEditable input with @mention support, cursor-positioned dropdown, and mention chip rendering.",
    files: ["mention-input/caret-utils.ts","mention-input/index.tsx","mention-input/mention-dropdown.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "pin-input",
    title: "PIN Input",
    description: "Masked numeric PIN input with show/hide toggle, paste support, and animated digit entry.",
    files: ["pin-input.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "currency-input",
    title: "Currency Input",
    description: "Formatted currency input with Intl.NumberFormat, searchable currency selector, and 30 currencies.",
    files: ["currency-input/currency-selector.tsx","currency-input/index.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "address-input",
    title: "Address Input",
    description: "Address autocomplete powered by OpenStreetMap Nominatim with split fields, map preview, and geolocation.",
    files: ["address-input/address-dropdown.tsx","address-input/index.tsx","address-input/map-preview.tsx","address-input/nominatim-utils.ts","address-input/split-fields.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "password-input",
    title: "Password Input",
    description: "Password field with show/hide toggle, real-time strength meter, and configurable requirements checklist.",
    files: ["password-input.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "rating-input",
    title: "Rating Input",
    description: "Interactive rating input with star, heart, emoji, and thumb variants, half-star precision, and labels.",
    files: ["rating-input.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "copy-button",
    title: "Copy Button",
    description: "One-click clipboard copy button with animated idle/copied/error states and tooltip feedback.",
    files: ["copy-button.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: ["tooltip"],
  },
  {
    name: "scroll-progress",
    title: "Scroll Progress",
    description: "Fixed scroll progress bar with spring physics. Supports top, bottom, left, and right positions.",
    files: ["scroll-progress.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "confetti",
    title: "Confetti",
    description: "Canvas-based confetti particle system with configurable colors, gravity, spread, and an imperative fire() API.",
    files: ["confetti/canvas.tsx","confetti/index.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "count-up",
    title: "Count Up",
    description: "Animated number counter with spring physics, in-view triggering, and Intl.NumberFormat formatting.",
    files: ["count-up.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "kbd",
    title: "Kbd",
    description: "Keyboard shortcut display with automatic platform detection and Mac/Windows symbol mapping.",
    files: ["kbd.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "code-editor",
    title: "Code Editor",
    description: "Monaco-powered inline code editor with multi-file tabs, diff mode, custom Bahrawy theme, run button, and output panel.",
    files: ["code-editor/diff-editor.tsx","code-editor/file-tabs.tsx","code-editor/index.tsx","code-editor/output-panel.tsx","code-editor/status-bar.tsx","code-editor/toolbar.tsx"],
    dependencies: ["@monaco-editor/react","framer-motion","lucide-react","monaco-editor"],
    shadcnComponents: ["select","tooltip"],
  },
  {
    name: "spreadsheet-input",
    title: "Spreadsheet Input",
    description: "Mini Excel-style editable grid with cell types, formulas, virtualization, CSV import/export, and clipboard support.",
    files: ["spreadsheet-input/cell.tsx","spreadsheet-input/column-header.tsx","spreadsheet-input/context-menu.tsx","spreadsheet-input/formula-bar.tsx","spreadsheet-input/index.tsx","spreadsheet-input/selection-overlay.tsx","spreadsheet-input/toolbar.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: ["checkbox"],
  },
  {
    name: "kanban",
    title: "Kanban",
    description: "Self-managing task board with drag-and-drop columns, subtasks, priority/difficulty pills, due dates, filters, list view, and localStorage persistence.",
    files: ["kanban/components/kanban/AddColumnTile.tsx","kanban/components/kanban/DifficultyBadge.tsx","kanban/components/kanban/TaskBoard.tsx","kanban/components/kanban/TaskCard.tsx","kanban/components/kanban/TaskColumn.tsx","kanban/components/kanban/TaskDialog.tsx","kanban/components/kanban/TaskFilterBar.tsx","kanban/components/kanban/TaskListView.tsx","kanban/components/ThemeProvider.tsx","kanban/components/ThemeToggle.tsx","kanban/components/ui/button.tsx","kanban/components/ui/calendar.tsx","kanban/components/ui/CompactEmojiPicker.tsx","kanban/components/ui/dropdown-menu.tsx","kanban/components/ui/input.tsx","kanban/components/ui/label.tsx","kanban/components/ui/LottieAnimation.tsx","kanban/components/ui/MobileBottomSheet.tsx","kanban/components/ui/popover.tsx","kanban/components/ui/select.tsx","kanban/components/ui/textarea.tsx","kanban/hooks/useIsMobile.ts","kanban/hooks/useLottie.ts","kanban/index.tsx","kanban/lib/lottie/colorInjector.ts","kanban/lib/lottie/themeColors.ts","kanban/lib/storage.ts","kanban/lib/uid.ts","kanban/lib/utils.ts","kanban/lib/validation.ts","kanban/store/useTaskBoardStore.ts","kanban/types/task.ts","kanban/utils/highlightText.tsx","kanban/utils/taskBadges.ts","kanban/utils/taskBoard.ts","kanban/utils/taskFilters.ts"],
    dependencies: ["@dnd-kit/core","@dnd-kit/sortable","@dnd-kit/utilities","@radix-ui/react-dialog","@radix-ui/react-dropdown-menu","@radix-ui/react-label","@radix-ui/react-popover","@radix-ui/react-select","@radix-ui/react-slot","class-variance-authority","clsx","date-fns","framer-motion","lottie-web","next-themes","react-day-picker","sonner","tailwind-merge","zod","zustand"],
    shadcnComponents: [],
  },
  {
    name: "virtual-list",
    title: "Virtual List",
    description: "High-performance virtualized list handling millions of rows. Fixed/variable height, grid, infinite scroll, grouped, table mode.",
    files: ["virtual-list/fixed-list.tsx","virtual-list/grid-list.tsx","virtual-list/group-header.tsx","virtual-list/index.tsx","virtual-list/scroll-to-top.tsx","virtual-list/search-bar.tsx","virtual-list/skeleton-rows.tsx","virtual-list/table-list.tsx","virtual-list/variable-list.tsx"],
    dependencies: ["@tanstack/react-virtual","framer-motion","lucide-react"],
    shadcnComponents: ["input"],
  },
  {
    name: "text-reveal",
    title: "Text Reveal",
    description: "Words, characters, or lines reveal with a smooth clip-mask slide-up animation triggered on scroll.",
    files: ["animations/text-reveal.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "typewriter-text",
    title: "Typewriter Text",
    description: "Classic typewriter effect with natural typing speed variation, delete-and-retype cycling, and blinking cursor.",
    files: ["animations/typewriter-text.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "blur-reveal",
    title: "Blur Reveal",
    description: "Content fades in from heavy blur to sharp focus with directional movement. Supports staggered children.",
    files: ["animations/blur-reveal.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "parallax-section",
    title: "Parallax Section",
    description: "Elements move at different speeds on scroll creating depth. Configurable speed and direction.",
    files: ["animations/parallax-section.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "stagger-reveal",
    title: "Stagger Reveal",
    description: "Container that automatically staggers its children in on scroll. Six direction modes.",
    files: ["animations/stagger-reveal.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "flip-text",
    title: "Flip Text",
    description: "Split-flap display effect where each character flips in with 3D rotation like a departures board.",
    files: ["animations/flip-text.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "text-scramble",
    title: "Text Scramble",
    description: "Characters scramble through random chars before resolving. Multiple charsets including binary, hex, and matrix.",
    files: ["animations/text-scramble.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "floating-elements",
    title: "Floating Elements",
    description: "Elements float and drift gently in random directions. Optional mouse repel physics.",
    files: ["animations/floating-elements.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "scroll-path-reveal",
    title: "Scroll Path Reveal",
    description: "Organic SVG path that draws itself as you scroll. GPU-driven via framer-motion pathLength — no layout reads, buttery smooth.",
    files: ["scroll-path-reveal/index.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "card-stack-scroll",
    title: "Card Stack Scroll",
    description: "Sticky-stacked cards inspired by Olivier Larose — each card scales gently as the next slides up on top. Pure framer-motion useScroll, GPU-only transforms.",
    files: ["card-stack-scroll/index.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "queue",
    title: "Queue",
    description: "Linear-style collapsible task groups. Spring-animated section toggles, soft round checkboxes with strikethrough on complete, optional avatars and sub-text per item.",
    files: ["queue.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "env-vars",
    title: "Env Vars",
    description: "Vercel-style environment-variable list. Monospace name, Required pill, masked dot values, per-row copy with checkmark, header eye-toggle reveals everything at once.",
    files: ["env-vars.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "tree",
    title: "Tree",
    description: "File-tree with rotating chevrons, folder/file lucide icons, gutter guide lines down the indent, hover row highlight, controlled or uncontrolled expanded state.",
    files: ["tree.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "ticker",
    title: "Ticker",
    description: "Inline stock ticker — logo, symbol, price, signed delta with up/down triangle. Flashes green/red on price change. Marquee row variant scrolls multiple tickers, pauses on hover.",
    files: ["ticker.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "snippet",
    title: "Snippet",
    description: "Install-command snippet with a tab bar (npm/pnpm/yarn/bun, or any tabs), spring-animated active pill, crossfaded code body, one-click copy with checkmark.",
    files: ["snippet.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "status",
    title: "Status",
    description: "Vercel-style service status display. Overall banner derives state from worst service (operational/degraded/outage/maintenance), per-service rows with 90-day uptime ribbons.",
    files: ["status.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "diff",
    title: "Diff",
    description: "GitHub-style unified code diff. File header with filename and +N/-N stats, monospace body with old + new line numbers, ± gutter glyph, tinted row backgrounds.",
    files: ["diff.tsx"],
    dependencies: ["lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "logs",
    title: "Logs",
    description: "Terminal-style log stream. Timestamp + colored level pill + optional [source] tag + message. Filter chips toggle visible levels, auto-scroll follows new entries.",
    files: ["logs.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "accordion",
    title: "Accordion",
    description: "Minimal accordion with a bouncy spring open/close. Single or multi-open, optional chevron, configurable bounciness.",
    files: ["accordion.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "image-hover-reveal",
    title: "Image Hover Reveal",
    description: "Image card whose description and CTA slide up over the image on hover. Spring-animated text lift + gentle image zoom.",
    files: ["image-hover-reveal.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "image-swap-text",
    title: "Image Swap Text",
    description: "Row of avatar thumbnails over a giant headline. Hovering an avatar swaps the headline to that avatar\\'s word — old letters fan outward while new letters pop in, with a tracker disc that follows the hover.",
    files: ["image-swap-text.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "scroll-rail",
    title: "Scroll Rail",
    description: "A pinned section whose children sit in a horizontal track and slide left as the page scrolls down. Spring-smoothed, auto-measured travel distance, optional progress bar.",
    files: ["scroll-rail.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "tabs",
    title: "Tabs",
    description: "Animated tab bar with a sliding indicator under the active tab and a fade-through on the content panel.",
    files: ["tabs.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "hover-card",
    title: "Hover Card",
    description: "Preview popup that appears with a delay on hover. Spring-positioned, fades + scales in.",
    files: ["hover-card.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "avatar-group",
    title: "Avatar Group",
    description: "Stacked overlapping avatars that spread apart on hover, with an overflow chip for hidden members.",
    files: ["avatar-group.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "progress-ring",
    title: "Progress Ring",
    description: "Circular progress indicator with animated stroke + spring-driven center label.",
    files: ["progress-ring.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "switch",
    title: "Switch",
    description: "Animated toggle switch with a spring thumb. Three sizes, controlled or uncontrolled.",
    files: ["switch.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "toast",
    title: "Toast",
    description: "Imperative toast notifications with useToast() hook, slide-in stack, intent variants (success/error/info), and auto-dismiss.",
    files: ["toast.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "skeleton",
    title: "Skeleton",
    description: "Shimmer placeholder for loading states. Rect, circle, pill shapes plus a multi-line SkeletonText helper.",
    files: ["skeleton.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "hero-spotlight",
    title: "Hero Spotlight",
    description: "Centered hero with a radial spotlight that follows the cursor. Spring-smoothed, tagline + headline + dual CTA.",
    files: ["hero-spotlight.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "hero-marquee",
    title: "Hero Marquee",
    description: "Centered hero on top of multi-row scrolling word marquees. Rows alternate direction and speed. Pauses on hover.",
    files: ["hero-marquee.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "hero-counter",
    title: "Hero Counter",
    description: "Hero layout with a giant stat that counts up on mount, plus a column of feature blurbs.",
    files: ["hero-counter.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "hero-aurora",
    title: "Hero Aurora",
    description: "Centered hero with drifting blurred color blobs behind the text. Soft, brand-y, configurable palette.",
    files: ["hero-aurora.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "pricing-tier",
    title: "Pricing Tier",
    description: "Three-tier card grid with a featured highlight + entrance stagger on scroll.",
    files: ["pricing-tier.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "pricing-toggle",
    title: "Pricing Toggle",
    description: "Pricing grid with monthly/annual billing toggle. Numbers spring-swap between modes.",
    files: ["pricing-toggle.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "pricing-compare",
    title: "Pricing Compare",
    description: "Feature comparison table with plan headers, group rows, and a highlighted recommended column.",
    files: ["pricing-compare.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "footer-minimal",
    title: "Footer Minimal",
    description: "Clean footer: logo + link columns + copyright. Light hover animations on links.",
    files: ["footer-minimal.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "footer-newsletter",
    title: "Footer Newsletter",
    description: "Footer with a prominent newsletter signup row. Submit button morphs to a Subscribed! confirmation.",
    files: ["footer-newsletter.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "footer-brand-mark",
    title: "Footer Brand Mark",
    description: "Footer with a giant wordmark across the bottom that fades + drifts into place on scroll, link columns above.",
    files: ["footer-brand-mark.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "stats-grid",
    title: "Stats Grid",
    description: "Section with 4 big counters that spring from 0 to their value on scroll. Optional per-tile color tint.",
    files: ["stats-grid.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "testimonials-slider",
    title: "Testimonials Slider",
    description: "Auto-rotating testimonial section with crossfade transitions and clickable indicator dots.",
    files: ["testimonials-slider.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "cta-section",
    title: "CTA Section",
    description: "Big call-to-action band with soft radial glows behind the headline. Customizable accent colors.",
    files: ["cta-section.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "faq-section",
    title: "FAQ Section",
    description: "Two-column FAQ layout: heading on the left, accordion of questions on the right.",
    files: ["faq-section.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "logo-cloud",
    title: "Logo Cloud",
    description: "\"Trusted by\" section with partner logos in an edge-faded marquee, or a static grid.",
    files: ["logo-cloud.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "bento-features",
    title: "Bento Features",
    description: "Feature bento grid section with mixed-size cards, accent gradients, scroll stagger.",
    files: ["bento-features.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "divider",
    title: "Divider",
    description: "Animated horizontal rule. Solid, dashed, or gradient. Optional centered label.",
    files: ["divider.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "banner",
    title: "Banner",
    description: "Sticky announcement banner with intent variants (info/success/warning/promo), CTA, dismissible.",
    files: ["banner.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "breadcrumb",
    title: "Breadcrumb",
    description: "Animated breadcrumb with chevron separators. Long trails collapse to a `…` menu.",
    files: ["breadcrumb.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "empty-state",
    title: "Empty State",
    description: "No-data pattern: icon in a glow ring, heading, body, and CTAs. Animated entry.",
    files: ["empty-state.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "loader-dots",
    title: "Loader Dots",
    description: "Classic three-dot typing/loading indicator. Configurable size, color, speed.",
    files: ["loader-dots.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "status-pill",
    title: "Status Pill",
    description: "Status badge with intent presets (online/away/busy/offline/error) and an optional pulsing dot.",
    files: ["status-pill.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "stat-card",
    title: "Stat Card",
    description: "Compact data card with animated number, delta badge, and inline sparkline.",
    files: ["stat-card.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "drawer",
    title: "Drawer",
    description: "Slide-in panel from any edge with a dim backdrop. Escape closes, spring entry.",
    files: ["drawer.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "tooltip",
    title: "Tooltip",
    description: "Lightweight tooltip primitive — for one-liners. Delay, side, smart entry direction.",
    files: ["tooltip.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "quote-card",
    title: "Quote Card",
    description: "Pull-quote card with author avatar + role and a scroll-triggered staggered reveal.",
    files: ["quote-card.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "search-input",
    title: "Search Input",
    description: "Standalone search field with an animated icon, clear button, debounced onSearch, and a loading spinner.",
    files: ["search-input.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "sparkline",
    title: "Sparkline",
    description: "Tiny SVG line chart that draws itself on mount. Optional area fill and end-point dot.",
    files: ["sparkline.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "pinned-story",
    title: "Pinned Story",
    description: "A cinema-style pinned narrative section. As the user scrolls, a GSAP timeline crossfades story steps, swaps images with parallax pan, switches the giant background number, shifts an accent tint, and drives a progress bar + side dot — all locked to scroll position.",
    files: ["pinned-story.tsx"],
    dependencies: ["@gsap/react","gsap"],
    shadcnComponents: [],
  },
  {
    name: "constellation-scroll",
    title: "Constellation Scroll",
    description: "GSAP + SVG section. A network/constellation diagram constructs itself stage-by-stage as the user scrolls — center node pops in, satellites stagger in, edges ink themselves, labels fade up, then pulse-dots fan outward from the center along every edge.",
    files: ["constellation-scroll.tsx"],
    dependencies: ["@gsap/react","gsap","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "mega-nav",
    title: "Mega Nav",
    description: "Floating top navigation bar with a frosted-glass backdrop. Hover a menu item with `sections` and a mega-menu drops down with categorized links — height + opacity animated, content fades between items, closes when the cursor leaves.",
    files: ["mega-nav.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "hero-scroll-grow",
    title: "Hero Scroll Grow",
    description: "Pinned hero. Text sits over an inset image card; as the user scrolls, a GSAP timeline grows the image from 72% to full-bleed, dissolves its border-radius, fades the hero text out, and (optionally) brings in an overlay caption.",
    files: ["hero-scroll-grow.tsx"],
    dependencies: ["@gsap/react","gsap","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "carousel-3d",
    title: "Carousel 3D",
    description: "Pinned 3D card carousel. Cards arc off to either side of an active centre card; scrubbed GSAP timeline advances `activeIndex` as the user scrolls, smoothly retargeting every card\\'s translateX / translateZ / rotateY / opacity / scale.",
    files: ["carousel-3d.tsx"],
    dependencies: ["@gsap/react","gsap"],
    shadcnComponents: [],
  },
  {
    name: "hero-split",
    title: "Hero Split",
    description: "Pinned hero with two 50/50 columns of stacked content that scroll in opposite Y directions (left up, right down). Past `reveal` (default 0.7) of the pin, a centred card fades in over both halves with a backdrop blur — the \"meeting\" moment.",
    files: ["hero-split.tsx"],
    dependencies: ["@gsap/react","gsap","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "phrase-slots",
    title: "Phrase Slots",
    description: "A slot-machine for words. Each \"slot\" is a single-line window with a tall column of candidate words behind it; scroll spins each column through multiple cycles, lands on the target with a staggered ending. Final state: a complete sentence reading across the row, underlined in the accent color.",
    files: ["phrase-slots.tsx"],
    dependencies: ["@gsap/react","gsap","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "magnetic-field",
    title: "Magnetic Field",
    description: "A pinned scroll section that pairs cursor magnetism with a scroll-driven wave. A canvas dot lattice repels around your cursor with a spring while a glowing accent line sweeps top-to-bottom; each headline locks in as the wave passes it, then a description and CTA fade in.",
    files: ["magnetic-field.tsx"],
    dependencies: ["@gsap/react","gsap","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "cursor-lens",
    title: "Cursor Lens",
    description: "An invisible cursor mask that reveals a different scene underneath as you hover. No ring, no chrome — just a soft radial fade so the boundary between the two scenes is impossible to spot. The inner image is gently magnified at the cursor focal point, the inner text is drawn crisp on top, and a click pins the lens at that spot so you can step back and look.",
    files: ["cursor-lens.tsx"],
    dependencies: ["lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "glitch-headline",
    title: "Glitch Headline",
    description: "A CRT-damaged display headline. Cyan + magenta channels drift in idle wobble; on hover a clip-path band sweeps the text and slices it horizontally, shifting chunks a few pixels out of register. Pure CSS, no animation loop, no JS runtime cost.",
    files: ["glitch-headline.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "type-tunnel",
    title: "Type Tunnel",
    description: "A pinned scroll section that turns a list of headlines into a Z-axis tunnel. Each line lives at a different depth in 3D space; scrolling moves the camera forward through them so they arrive from the vanishing point, swell to fill the viewport, then pass behind you. One final standing headline lands at the end.",
    files: ["type-tunnel.tsx"],
    dependencies: ["@gsap/react","gsap","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "paper-tear",
    title: "Paper Tear",
    description: "Two sheets of paper stacked on top of each other. As you scroll into the section, the top sheet tears off along a deterministic jagged SVG path and lifts away with a subtle tilt + fade, revealing the bottom sheet. Both halves carry a paper-grain texture so the tear reads physical.",
    files: ["paper-tear.tsx"],
    dependencies: ["@gsap/react","gsap","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "liquid-letters",
    title: "Liquid Letters",
    description: "A typography effect that makes letters look like blobs of liquid. The classic CSS-goo SVG filter (Gaussian blur + alpha-tightening colour matrix) is applied to both the SVG text AND a cursor-following blob — so the blob bonds with whichever letters it touches and pulls them into a single fluid shape.",
    files: ["liquid-letters.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "depth-cards",
    title: "Depth Cards",
    description: "A 3D diorama. Layered cards sit at different Z depths inside a perspective container; moving your cursor tilts the camera so the cards parallax against each other. Spring-eased tilt, per-card counter-parallax, depth-falloff glow halos — look-around at depth, no scroll required.",
    files: ["depth-cards.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "wave-text",
    title: "Wave Text",
    description: "A line of text where each character undulates in a sine wave with a staggered phase. Pure CSS — no JS animation loop.",
    files: ["wave-text.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "disperse-text",
    title: "Disperse Text",
    description: "Letters explode away from their resting position on hover then settle back when the cursor leaves. Per-character offsets seeded by index for stable layout.",
    files: ["disperse-text.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "magnetic-text",
    title: "Magnetic Text",
    description: "Every character has a magnetic pull toward the cursor — yanked along the cursor vector with strength proportional to proximity, lerped per frame for a spring-like feel.",
    files: ["magnetic-text.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "variable-font-morph",
    title: "Variable Font Morph",
    description: "Each character animates its `font-variation-settings: 'wght'` axis between two values with a staggered phase. Works with any variable font that exposes a weight axis.",
    files: ["variable-font-morph.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "gradient-flow",
    title: "Gradient Flow",
    description: "Text whose fill is a linear gradient sized 300% of the text width; animating background-position slides the colors through the glyphs in a seamless loop.",
    files: ["gradient-flow.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "holo-text",
    title: "Holo Text",
    description: "Holographic text: a cyan layer and a magenta layer drift in opposite directions behind a white base layer, blending in `screen` mode so the overlap reads white but the fringes glow.",
    files: ["holo-text.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "shine-sweep",
    title: "Shine Sweep",
    description: "A bright \"shine\" stripe sweeps diagonally across the text. Background-clip: text + animated background-position. Runs continuously or only on hover.",
    files: ["shine-sweep.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "char-spring",
    title: "Char Spring",
    description: "Each character springs up from below when the element enters the viewport. Container overflow-hidden + per-char delay for a typewriter-with-bounce feel.",
    files: ["char-spring.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "stretch-text",
    title: "Stretch Text",
    description: "Move the cursor across the line — each letter widens via Gaussian falloff against the cursor X, then springs back. Per-letter scaleX + letter-spacing, Apple spring physics.",
    files: ["stretch-text.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "time-dial",
    title: "Time Dial",
    description: "A pinned scroll section built around a giant rotating dial. Chapters sit around the perimeter at evenly-spaced angles; scroll rotates the dial clockwise so each chapter passes under a top pointer, and the content panel on the right crossfades to that chapter.",
    files: ["time-dial.tsx"],
    dependencies: ["@gsap/react","gsap","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "receipt-unroll",
    title: "Receipt Unroll",
    description: "A paper receipt unrolls from a printer slot at the top as you scroll. Header, line items type in one at a time, subtotal/total animate at the bottom, scalloped edges + barcode at the very bottom.",
    files: ["receipt-unroll.tsx"],
    dependencies: ["@gsap/react","gsap","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "orbital-menu",
    title: "Orbital Menu",
    description: "A FAB-style trigger button that fans its menu items outward along an arc on click. Per-item spring stagger, configurable direction (top / right / bottom / left / circle), click outside or Escape to close.",
    files: ["orbital-menu.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "habit-heatmap",
    title: "Habit Heatmap",
    description: "GitHub-style contribution grid. 7 rows × N weeks, cell intensity scales with value through a 5-step accent ramp. Weekday axis, month markers, \"Less → More\" legend, hover tooltips. Drop in data — or fall back to a stable demo grid.",
    files: ["habit-heatmap.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "cassette-tape",
    title: "Cassette Tape",
    description: "Vintage audio cassette with rotating reels, tape line between them, label with side/title/duration, play/pause button, and a 3D flip to switch between A-side and B-side.",
    files: ["cassette-tape.tsx"],
    dependencies: [],
    shadcnComponents: [],
  },
  {
    name: "like-burst",
    title: "Like Burst",
    description: "Heart button that fills + scales + emits a radial particle burst on click. Click again to un-like (no burst). Controlled or uncontrolled, optional running count.",
    files: ["like-burst.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "mood-slider",
    title: "Mood Slider",
    description: "Apple-style mood slider — clean white handle that scales on hover and drag, hue-shifting gradient track (indigo → pink by default), snap-to-step values for a tiny haptic feel, animated mood word in the header.",
    files: ["mood-slider.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "split-panel",
    title: "Split Panel",
    description: "Two panes with a draggable divider. Drag to resize; cross min/max and the panel rubber-bands. Optional snap points. Horizontal or vertical, full keyboard support.",
    files: ["split-panel.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "image-compare",
    title: "Image Compare",
    description: "Drag-to-wipe before/after slider. Top image is clipped via CSS clip-path at handle position; click or drag anywhere to move. Horizontal or vertical, keyboard nav.",
    files: ["image-compare.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "audio-player",
    title: "Audio Player",
    description: "Real audio player around <audio>. Play/pause, time, volume + mute, and a waveform-as-seek-bar where bars left of the playhead glow accent-colored. Click to seek, drag to scrub.",
    files: ["audio-player.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "bar-chart",
    title: "Bar Chart",
    description: "Single-series categorical bar chart. Animated entrance per bar, hover lift + tooltip, optional gridlines + value labels, per-bar colors, niced-up max. Vertical or horizontal.",
    files: ["bar-chart.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "sidebar-nav",
    title: "Sidebar Nav",
    description: "Apple-style app sidebar navigation primitive. Vibrancy panel, grouped + collapsible sections, animated active-item pill via layoutId, icon + label + optional badge, optional sticky footer.",
    files: ["sidebar-nav.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "image-lightbox",
    title: "Image Lightbox",
    description: "Click-to-zoom gallery with vibrancy backdrop, prev/next arrow + on-screen controls, arrow-key navigation, swipe-to-navigate on touch, optional caption pill, counter chip, and Esc to close.",
    files: ["image-lightbox.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "floating-toolbar",
    title: "Floating Toolbar",
    description: "Notion/Linear-style selection action bar. Highlight text → vibrancy pill toolbar floats above the selection (auto-flips below if no room), each action fires with the selected text + rect.",
    files: ["floating-toolbar.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "segmented-control",
    title: "Segmented Control",
    description: "iOS-style segmented picker. Pill wrapper with vibrancy, animated white indicator pill sliding between segments via layoutId, supports icons + labels, three sizes, optional full-width.",
    files: ["segmented-control.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "line-chart",
    title: "Line Chart",
    description: "Stripe/Linear-style smooth line chart. Catmull-Rom-to-bezier smoothing, accent gradient fill, animated pathLength entrance, hover crosshair + vibrancy tooltip pinned to the nearest data point, niced Y-axis ticks.",
    files: ["line-chart.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "dialog",
    title: "Dialog",
    description: "Apple-style centered modal. Vibrancy backdrop with blur, scale-in spring entrance, focus trap with restore-on-close, ESC + backdrop click to dismiss, body scroll lock, title + description + footer slots, destructive intent.",
    files: ["dialog.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "popover",
    title: "Popover",
    description: "Anchored interactive popup. Controlled open, anchor via ref, side + align placement, auto-flip on insufficient room, vibrancy panel with optional arrow, click-outside + ESC dismiss, repositions on scroll/resize.",
    files: ["popover.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "activity-rings",
    title: "Activity Rings",
    description: "Apple Watch-style concentric fitness rings. Each ring has value/goal/color, animated pathLength entrance, overshoot draws a brighter second pass on top. Soft glow per ring, optional center stat + legend.",
    files: ["activity-rings.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "donut-chart",
    title: "Donut Chart",
    description: "Animated SVG donut chart. Each slice draws in clockwise via dasharray animation, hover lifts the slice outward along its midpoint vector, vibrancy tooltip with value + %, center label slot, interactive legend.",
    files: ["donut-chart.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "slider",
    title: "Slider",
    description: "Apple-style range slider. Supports single value or [low, high] range, ticks, value tooltip on hover/drag, keyboard nav. Clean white disc handle with Apple spring on hover/drag scale.",
    files: ["slider.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "pagination",
    title: "Pagination",
    description: "Apple-style page navigator. Numbered pills with ellipsis-collapsing for long ranges (always shows first, last, window around current), prev/next chevrons, layoutId-driven active pill that glides between pages.",
    files: ["pagination.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "toggle-group",
    title: "Toggle Group",
    description: "Multi-select pill row. Cousin of Segmented Control but selection is a Set, not a single value. Two visual modes: pills (separate, breathing room) or segmented (joined). Three sizes, icons + labels.",
    files: ["toggle-group.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "calendar",
    title: "Calendar",
    description: "Apple-style standalone month-grid date picker. Single or multiple date selection, locale-aware weekday names, today indicator dot, layoutId-driven selection that glides between days, month navigation.",
    files: ["calendar.tsx"],
    dependencies: ["framer-motion","lucide-react"],
    shadcnComponents: [],
  },
  {
    name: "reactions-picker",
    title: "Reactions Picker",
    description: "Slack/Messages-style emoji reactions popup. Row of emojis with macOS Dock-magnification on cursor proximity, click fires onPick. Vibrancy pill, Apple spring on the magnify scale.",
    files: ["reactions-picker.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
  {
    name: "bottom-tab-bar",
    title: "Bottom Tab Bar",
    description: "iOS-style mobile bottom navigation. Floating vibrancy pill with 3-5 tabs, icon + label, active tab gets a soft white pill that glides between tabs via layoutId, optional badge per tab.",
    files: ["bottom-tab-bar.tsx"],
    dependencies: ["framer-motion"],
    shadcnComponents: [],
  },
]

/**
 * Shared files every Bahrawy component depends on.
 * Copied once if they don't already exist.
 */
export const sharedFiles = [
  { src: 'lib/utils.ts', dest: 'lib/utils.ts' },
]

export const GITHUB_RAW_BASE =
  'https://raw.githubusercontent.com/bahrawyX/bahrawy-picks/main'

export function getEntry(name: string): RegistryEntry | undefined {
  return registry.find((e) => e.name === name)
}
